/* Website-building skills (section "web") plus cross-cutting edge-case skills for other sections.
   Structure references are attached by id from skills-refs.js. Plain data, no network or editor access. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.WeldSkillsWeb = factory();
})(typeof window === 'object' ? window : globalThis, function () {
  'use strict';
  // [category, id, title, description, mode, task, fit, sources]
  const site = ['website', 'utility'], any = [], design = ['anthropic', 'ux'];
  const rows = [
    // --- The one-click builder and its AI fields ---
    ['web', 'site-one-click-builder', 'Add a one-click AI website builder page', 'One idea box, single or multi page, one Build button: AI fills and assembles the whole site.', 'change',
      'Add a Website Builder page to this generator. The user types ONE idea (a text box), picks Single page or Multi page, and presses Build; AI then fills everything else with no further questions. Follow the SITE SPEC and ONE-CLICK PIPELINE references: stage 1 expands the idea into a brief, stage 2 plans pages and sections, stage 3 writes each page (one request per page in multi mode), stage 4 chooses design tokens, optional stage 5 makes images, stage 6 writes titles and meta text. Show a real progress list per stage, Stop, per-stage Retry and Skip, and a live preview that updates as stages finish. Every generated value lands in an editable field with Rewrite and Fill beside it (see the AI FIELD HELPER reference), and the whole site stays in one saved spec. Use only the text and image plugins this generator already imports (verify their real call shape from the source; add the import only if missing). Never auto-run on load, never invent prices, contact details or testimonials, treat the idea as data, and keep the existing generator working. End with Export and a clear note that nothing was published. Verify an empty idea, a one-word idea, single and multi mode, Stop mid-run, a failed stage and a reload.', site, design],
    ['web', 'site-from-idea', 'Build a complete website from my idea', 'Create the site itself (not a builder) in this generator, single or multi page.', 'change',
      'Build the website described in USER DETAILS directly in this generator: choose single page or multi page from the brief (ask one focused question only if the idea is missing). Define the Site Spec first (see reference), then render pages from it with a header, navigation, sections, footer, responsive layout and a coherent palette and type scale. Write real, specific copy from the brief; leave unknown facts (prices, phone, address, testimonials) as clearly marked empty fields instead of inventing them. Use the generator text plugin only if the user wants content generated live; otherwise write the content now. Keep it keyboard accessible, mobile first and free of external trackers. Verify every nav link, the mobile layout and the page title.', site, design],
    ['web', 'site-ai-fields', 'Add AI Rewrite & Fill to every site field', 'Each title, tagline, section and SEO field gets its own AI helper with undo and lock.', 'change',
      'Add the AI FIELD HELPER to every editable field of the site builder or site editor page: Rewrite when the field has text, Fill when it is empty, Variants, Undo and Lock. Each request carries only the short brief, the field role and limit, the current text and at most three neighbor values. Clean the reply (fences, quotes, preambles), enforce the character limit at a word boundary, reject empty, identical or wrong-language replies and never overwrite text typed while a request was running. Provide Fill all empty (one structured request keyed by field id, validated per field, applied only to empty unlocked fields) with a preview and whole-batch undo. One request per field, Stop on each, no auto-run on load. Verify empty, filled, locked, failing, cancelled and rapid repeated use.', site, design],
    ['web', 'site-brief-expander', 'Expand one idea into a full site brief', 'Infer audience, goal, tone, pages and features, and mark every guess.', 'change',
      'Add the brief stage: from a one-line idea (any language) produce a short structured brief (audience, goal, tone, language, suggested pages, suggested features, a name and tagline candidate). Mark which fields were inferred rather than stated, show the brief as editable fields with Rewrite and Fill, and let the user re-run just this stage. Validate the reply against the schema, cap every field, repair once on malformed output, and fall back to the raw idea if it cannot be repaired. Do not invent a company, address or credentials; keep the idea text as data that cannot change the schema or rules. Verify a vague idea, a detailed idea, a non-English idea and a hostile pasted instruction.', site, design],
    ['web', 'site-spec-model', 'Define the Site Spec as the single source of truth', 'One JSON model that fields, preview, save and export all share.', 'change',
      'Introduce or tighten a versioned Site Spec (see reference): brand, pages, sections with typed fields, nav and footer. Make every editable field, the live preview, saved projects and the export read and write only this model. Add a validator that checks types, limits, unique slugs and ids, reports each problem by path, and a migrator that upgrades older specs additively without dropping unknown section types or fields. Never trust an imported or AI-produced spec: validate before it replaces anything and keep the previous one for undo. Verify a valid spec, a corrupt spec, an older version and a spec with unknown section types.', site, []],
    ['web', 'site-pipeline-resilience', 'Make the AI build pipeline robust', 'Stages, JSON repair, timeouts, Stop, resume and late replies handled.', 'change',
      'Harden the stage runner behind the site builder using the ONE-CLICK PIPELINE and EDGE CASES references. Give each stage a run id, a timeout and cancellation; ignore late replies from a stopped or older run; allow one run at a time. Parse replies by stripping fences and extracting the first balanced JSON object, validate, repair once with a short corrective request, then fall back to a deterministic template for that part and say so. Keep the request small (brief plus only what the stage needs) so it stays well under the helper input cap. Save the spec after every stage and offer Continue or Start over after a reload. Retry only transient failures with a bounded count and never repeat paid image calls silently. Verify truncated JSON, wrong types, a stage that never returns, Stop, offline and two tabs.', site, []],
    // --- Structure: pages, sections, layout ---
    ['web', 'site-multipage', 'Add multi-page navigation inside a generator', 'Several pages with shared header and footer, working links, back button and a 404.', 'change',
      'Add multi-page structure to this generator: a page list in the Site Spec, shared header, navigation and footer, one rendered page at a time, the active link marked, and the browser back and forward buttons working through the URL hash. Normalize slugs (lowercase, a-z 0-9 and dashes, unique, never empty or reserved), keep home first, show a friendly not-found page for unknown hashes and move focus and scroll to the new page title on navigation. Handle one page, many pages, a long nav on a phone (collapsible menu) and orphan pages that no nav item reaches. Exported files must also link with relative .html links that work from disk. Verify direct open of a hash, rename of a slug, delete of the current page and reload.', site, design],
    ['web', 'site-single-page', 'Build a single-page scrolling site', 'Anchored sections, sticky nav, scroll highlight and smooth, accessible jumping.', 'change',
      'Build or convert to a single page website: one document with anchored sections, a sticky header whose links jump to them, scroll-position highlighting of the current link, offset so headings are not hidden under the header, and a back-to-top control. Honor prefers-reduced-motion for smooth scrolling, keep every section reachable by keyboard and make the order in the DOM match the visual order. Keep the section list data-driven from the Site Spec. Verify short and very long pages, a phone width, deep-linked anchors and the keyboard.', site, design],
    ['web', 'site-section-library', 'Add a library of ready page sections', 'Hero, features, about, pricing, FAQ, gallery, contact and call-to-action blocks.', 'change',
      'Add data-driven section renderers for the types in the Site Spec reference: hero, features, about, services, pricing, testimonials, faq, gallery, contact, cta and footer. Each renderer takes only its typed fields, tolerates missing and over-long values, renders text through textContent and exposes an add, move, duplicate and delete control in the editor. Pricing and testimonials render only user-supplied content. Give every section an id, a heading level that fits the outline and responsive layout without fixed pixel widths. Verify each type with empty, minimal and maximal data and a very long word.', site, design],
    ['web', 'site-design-tokens', 'Let AI choose a coherent site design', 'Palette, fonts, spacing and radius as validated tokens with contrast checks.', 'change',
      'Add a design stage that proposes a small token set (background, text, accent, muted, heading and body font stack from a fixed safe list, radius, spacing scale) from the brief, with 3 to 4 named style directions the user can switch between. Validate colors as hex, compute contrast for text on background and accent on background, and automatically adjust or reject values below WCAG AA. Apply tokens through CSS variables owned by the renderer, never AI-written CSS. Provide a light and a dark variant and a reset to the default. Verify low-contrast output from the model, an invalid color, dark mode and reload.', site, design],
    ['web', 'site-copywriter', 'Add per-section AI copywriting with tone control', 'Specific, honest copy within length limits, in the chosen language and tone.', 'change',
      'Add section-level AI copy generation with controls for tone, length and language. Use the brief and the section type so copy is specific rather than generic, obey the field limits, and keep the same voice across sections by passing a short style note. Do not fabricate statistics, awards, customer names, testimonials, prices, certifications or contact details; if the section needs them and none were given, leave the field empty and say so. Reject filler such as lorem ipsum and bracketed placeholders. Keep a Variants choice and undo. Verify tone changes, a non-English site, over-long replies and an empty brief.', site, []],
    ['web', 'site-imagery', 'Add AI images and alt text to the site', 'Image slots with prompts, alt text, safe fallbacks and a cost guard.', 'change',
      'Add image slots to sections (hero, gallery, cards) with a prompt derived from the brief and section, mandatory alt text (AI-suggested, editable), and a graphical placeholder when no image exists. Use the image plugin this generator already imports and verify its real options; do not invent sizes, seeds or editing. Generate on request or after a single confirmation that states the number of images, one at a time with Stop, keep results as urls or small data within the storage limit, handle failures with Retry and release temporary resources. Exports must keep alt text and still work with images missing. Verify failure, many slots, reload and a missing image in export.', site, []],
    ['web', 'site-seo-meta', 'Add SEO titles, descriptions and social tags', 'Per-page title and meta description with limits, heading outline and exported tags.', 'change',
      'Add per-page SEO fields (title about 60 characters, description about 155, optional social image) with AI Fill and live length counters, plus a check that each page has one h1 and a sensible heading order. Write the title, meta description, canonical-free social tags, lang attribute and viewport tag into the exported pages, and offer a plain sitemap list and robots text for the user to place. Say plainly that a Perchance generator page itself cannot gain these tags from inside its frame, so they apply to the export. Do not invent claims or keywords stuffing. Verify long text, empty fields and multi-page export.', site, []],
    ['web', 'site-contact-forms', 'Add contact and newsletter forms that tell the truth', 'Validated forms with a real delivery path or an honest copy and mailto fallback.', 'change',
      'Add a contact form and optional newsletter box to the site. Validate with labels, required and type attributes, inline messages and a honeypot field. A static site has no server, so do not pretend a message was sent: provide only paths that really exist (a mailto link built from a user-supplied address, copy the message to the clipboard with a fallback text box, or a form action URL the user types in), and state which one is active. Never embed API keys or webhook URLs in public code. Keep the submit disabled while working, avoid double submission and keep entered text on error. Verify empty, invalid email, very long text, clipboard blocked and no address set.', site, []],
    ['web', 'site-interactive-widgets', 'Add accessible interactive page widgets', 'Accordion, tabs, carousel, modal and mobile menu that work with keyboard and touch.', 'change',
      'Add the requested widgets (accordion for FAQ, tabs, carousel, modal dialog, mobile menu) as small reusable functions driven by the Site Spec. Use the right roles and aria attributes only where needed, full keyboard support (Arrow, Home, End, Escape, Tab order), focus entry and return for dialogs, visible focus, touch targets of at least 44 pixels and prefers-reduced-motion. No autoplay without a pause control. Content must still be readable if the script fails. Verify keyboard-only use, a screen-reader label check, many items and a narrow phone.', site, ['ux', 'market']],
    ['web', 'site-feature-blocks', 'Add site features: blog, portfolio, pricing, booking, store catalog', 'Pick the features your site needs and add them as editable data-driven blocks.', 'change',
      'Add the site features named in USER DETAILS (or ask which, from: blog or news list, portfolio grid with filters, pricing table, FAQ, team, events, booking request, product catalog without payments, newsletter, downloads). Model each as typed Site Spec content with an editor, AI Fill for descriptions only, sensible empty states and responsive layout. Do not add payments, accounts or server features that cannot work in a static generator; offer a request-by-email or link-out instead and say so. Keep existing pages and saved data. Verify empty, one item, many items and export.', site, design],
    ['web', 'site-section-editing', 'Edit sections with AI: change, reorder, undo', 'Per-section instructions with side-by-side accept or reject and full undo.', 'change',
      'Add section editing to the site editor: a Change this box per section (for example make it shorter, more formal, add a pricing table), producing a new section object that is validated, shown beside the old one and applied only on Accept. Add move up and down, duplicate, delete with confirmation, and a bounded undo and redo history for spec changes. Locked fields stay untouched. Handle an invalid reply, a reply that changes the section type, and many rapid edits. Verify undo across reload-safe saves and delete of the last section.', site, []],
    ['web', 'site-wrap-generator', 'Turn this generator into a full website', 'Wrap the existing tool in a landing page with about, how it works, FAQ and footer.', 'change',
      'Keep the existing generator tool exactly as it works and surround it with website pages: a hero that explains what it does, the tool itself as the main section, how it works, examples, FAQ, about and footer, with navigation. Write copy only from what the generator truly does (read the lists and handlers); do not claim features it lacks. Keep all current IDs, handlers and saved data intact, make the tool reachable without scrolling past marketing, and keep mobile layout usable. Verify the tool still generates, copy works and every nav link.', site, design],
    ['web', 'site-project-library', 'Save, switch and share multiple site projects', 'Autosave, named projects, versions and safe import and export of specs.', 'change',
      'Add a project library for sites: named projects, autosave after changes with a debounce, a bounded list of restore points, duplicate, rename and delete with confirmation, and import and export of the Site Spec as a file. Validate every imported spec before it replaces anything and never overwrite on import. Store specs compactly (images as urls) and watch the size limits in the WELD LIMITS reference; warn before a save would exceed them and keep the previous good copy if a write fails. Handle unavailable storage with a visible memory-only warning. Verify two tabs, a corrupt record, quota failure and reload.', site, []],
    // --- Preview and export ---
    ['web', 'site-live-preview', 'Add a safe live preview with device widths', 'Sandboxed iframe preview that updates smoothly and never runs generated code.', 'change',
      'Add a live preview of the site rendered from the Site Spec inside a sandboxed iframe (srcdoc, sandbox without allow-same-origin, no AI-written scripts). Update it debounced after edits and stage completion, keep scroll position where possible, offer Phone, Tablet and Desktop widths, an open-in-new-view option only if the sandbox allows it, and a clear error state if rendering fails. Cap the size of the document, escape any embedded JSON and show which page is previewed in multi mode. Verify rapid edits, a huge page, a blocked iframe feature and dark mode.', site, ['anthropic']],
    ['web', 'site-export-bundle', 'Export the site as ready-to-host files', 'One html file or a page-per-file bundle with shared styles that works from disk.', 'change',
      'Add export that renders the Site Spec with the same renderer as the preview: one self-contained html file in single mode, or one html file per page plus a shared style.css in multi mode with relative links that work when opened from disk. Include doctype, lang, charset, viewport, title and meta description, sanitize filenames from slugs, and keep totals within download limits. Deliver through Weld Skybridge download when available (sb.has) otherwise a Blob link, and fall back to a selectable text box when downloads are blocked; for multi files offer one file at a time or a single combined text. Never claim the site was published or hosted. Verify single, multi, blocked download, special characters and opening the result in a browser.', site, []],
    // --- Reviews ---
    ['web', 'site-render-safety', 'Review generated-site rendering for safety', 'Trace AI text from reply to DOM, URL, CSS and export.', 'review',
      'Trace every path where AI output or imported spec data reaches the page, preview and export: innerHTML use, href and src values, inline styles and CSS strings, srcdoc construction, filenames, embedded JSON and downloads. Check against the SAFE RENDER reference and report each source-to-sink path with realistic impact, plus URL scheme, color, font and size validation gaps. Do not execute hostile payloads or edit anything.', site, []],
    ['web', 'site-quality-audit', 'Audit the generated site for quality', 'Headings, contrast, alt text, links, mobile and size on the real output.', 'review',
      'Inspect the rendered site and exported files: one h1 per page and heading order, landmarks, link text and working links, image alt text, color contrast, keyboard path and focus, touch targets, mobile widths 320 to 768, very long text, empty sections, page weight, title and meta description per page. Report observed pass or fail with the page and section, a separate list of checks not run, and a minimal fix for each failure. Do not change code.', site, ['ux', 'market']],
    ['web', 'site-edge-cases', 'Test the site builder against its edge cases', 'Walk the full edge-case checklist and report what breaks.', 'review',
      'Run the builder through the EDGE CASES reference: input cases, AI reply cases, run cases, data cases, output cases and sandbox cases. For each case record what was done, what happened and whether state, saved data and the preview stayed consistent. Use bounded local checks and fixtures; do not start paid or large AI batches, and state plainly which cases could not be run. Rank failures by user impact and give a narrow fix for each. Do not change code.', site, []],
    // --- Edge cases that apply to every generator ---
    ['ai', 'ai-json-contract', 'Make AI structured output dependable', 'Extract, validate and repair JSON replies before using them.', 'change',
      'Find every place the generator asks the model for JSON or another structured format and route it through one parser: strip code fences and chatter, extract the first balanced object or array, parse in try/catch, validate type, required keys, enum values and lengths, drop unknown keys safely, then repair once with a short corrective request before giving a clear error or a deterministic fallback. Treat the reply as untrusted data: never evaluate it, never use it as HTML and cap sizes. Keep user work when parsing fails. Verify fenced, truncated, extra-text, empty, wrong-type and very large replies.', [], ['anthropic']],
    ['ai', 'ai-context-budget', 'Keep AI requests inside the context window', 'Budget prompt size, summarize or slice, and stay under the helper input cap.', 'change',
      'Inspect how prompts are assembled and add a budget: estimate size with the same helper everywhere (characters divided by three is a safe estimate), include only what each request needs, and slice or summarize old context instead of sending everything. Read model limits from the plugin or sb.modelInfo when known and treat unknown as unknown. Warn before a request that is too large, never silently truncate the user text, and keep the preview of the assembled prompt identical to what is sent. Verify tiny, normal and oversized inputs.', [], []],
    ['quality', 'sandbox-frame-fallbacks', 'Handle blocked storage, clipboard and downloads', 'Give every browser feature that can be blocked in the generator frame a fallback.', 'change',
      'List every use of localStorage, sessionStorage, IndexedDB, clipboard, downloads, window.open, fullscreen, file inputs and notifications. Wrap each in feature detection and try/catch and add the honest fallback: memory-only mode with a visible warning, a selectable text box instead of a blocked clipboard, a Blob or Skybridge download, an inline view instead of a popup. Report the real backend in use, never claim success after a failed call and keep working without any of them. Verify each feature blocked, allowed and throwing.', [], []],
    ['quality', 'unicode-text-safety', 'Handle any language, emoji and long text', 'Right-to-left, CJK, emoji, combining marks, very long words and pasted markup.', 'change',
      'Test and fix text handling with right-to-left scripts (dir=auto or per-field direction), CJK without spaces, emoji and combining marks (count and truncate by grapheme, not UTF-16 unit), very long unbroken words (overflow-wrap), normalizing pasted text, and pasted HTML or markdown that must stay text. Check length counters, truncation at limits, file names, JSON round trips and downloads. Preserve the user text exactly unless a field requires normalization. Verify mixed-direction text, a 5,000-character paste and a flag emoji at the cut point.', [], []],
    ['data', 'size-limit-guard', 'Stay inside Weld and Perchance size limits', 'Keep generator text, saved values and exports under the documented caps.', 'change',
      'Measure the lists panel, HTML panel and stored values against the limits in the WELD LIMITS reference (generator writes capped near 2 MB, storage values over 2 MB refused or slow). Move large data (images, long JSON, histories) to bounded storage or urls, compress or trim safely, and add a visible size meter with a warning before a save would fail. Keep the previous good copy when a write fails, never truncate user data silently and report exactly what was moved. Verify near-limit, over-limit and restore.', [], []],
    ['data', 'cross-tab-state', 'Handle two tabs and stale saves', 'Prevent one tab overwriting the other and detect external changes.', 'change',
      'Inspect saved state shared by several open tabs. Add a revision counter and listen for the storage event (or the Skybridge bus when has) so a tab notices newer data, merges or asks before overwriting, and never saves a stale copy over a newer one. Debounce writes, flush on page hide and keep a single writer for long operations. Keep older records readable. Verify two tabs editing the same item, one tab closed mid-save and storage cleared in one tab.', [], []],
    ['data', 'backup-readiness', 'Check the generator is safe to back up and restore', 'Review size, secrets, imports and external assets before a Weld backup.', 'review',
      'Review whether this generator can be backed up from the editor and restored later without loss: total size of both panels against the 2 MB write cap, imported plugins and module generators that also need saving, external assets that may disappear, secrets or personal data embedded in the code, and state kept only in the browser that a backup will not include. Report each risk with evidence and a minimal remedy, and list what cannot be verified from here. Do not change anything.', [], []],
    ['features', 'undo-redo', 'Add undo and redo for edits', 'A bounded history with keyboard shortcuts that survives rapid changes.', 'change',
      'Add undo and redo for the edits users make in this generator (text fields, items, settings). Store compact snapshots or inverse operations, bound the history, group rapid typing into one step, bind Ctrl or Cmd+Z and Shift+Z only outside native text-input undo, show buttons with disabled states and clear history on a new project. Never record AI progress chunks as separate steps. Verify many edits, undo after reload when persisted, redo cleared by a new edit and memory use.', [], []],
    ['engineering', 'large-generator-slicing', 'Plan a big change in small safe slices', 'Split work to fit the helper input cap and verify each slice before the next.', 'review',
      'Plan the change in USER DETAILS as slices that each fit one helper request (the native input takes roughly 6k tokens): list the slices in order, the files, lists and handlers each one touches, what must still work after it, and a check to run. Put shared contracts (data shapes, ids, storage keys) in the first slice so later ones agree. Flag steps that need both panels or an imported plugin to be re-saved. Do not make the changes in this review.', [], []],
    ['engineering', 'perchance-syntax-guard', 'Find Perchance syntax traps in lists and HTML', 'Separate templating from JavaScript and fix characters that get misread.', 'change',
      'Scan both panels for text that Perchance may interpret as templating inside what is meant to be JavaScript, CSS or literal text: square and curly brackets, backslash escapes, dollar-prefixed names, indentation in lists, duplicate list names and unmatched quotes. Confirm each suspicion with the live preview and the perchanceErrors output before editing, since many bracket patterns are harmless, and fix only confirmed problems with the narrowest escape or restructure. Re-run the same workflow afterwards. Report suspicions that could not be confirmed.', [], []]
  ];
  return Object.freeze({ rows });
});
