/* Dad-Chat skill rows: tasks for working on a Dad Chat (dad-chat-v2) Perchance project.
   Structure diagrams and worked examples are attached by id from skills-refs.js. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.WeldSkillsDad = factory();
})(typeof window === 'object' ? window : globalThis, function () {
  'use strict';
  // The section id, title and guide text live in skills-core.js (categories, guides).
  // [category, id, title, description, mode, task, fit, sources]
  const fit = ['chat', 'story'], src = ['dad-arch', 'dad-format'];
  const rows = [
    // --- Orient, diagnose, fix ---
    ['dad', 'dad-orient', 'Map the project against the layout', 'Confirm the real files match the diagram and report any drift.', 'review',
      'Compare the open project with the DAD-CHAT LAYOUT diagram: list main.pjs imports and knobs, the index.html hub server block, every script tag in load order, src/styling.css and the built-in presets. For each documented file report present, missing, renamed or moved, with the exact search you ran. Locate window.* handles (DadAgentCore, Dad_PROVIDER_GROUPS, ImageForge, WS, StoryForge, SceneCast) and confirm which file defines each. Report where the documentation and code disagree so the documentation can be fixed; do not edit anything.', fit, src],
    ['dad', 'dad-diagnose', 'Diagnose a Dad-Chat problem', 'Trace a symptom through the chat-turn flow to the exact file and function.', 'review',
      'Diagnose the problem in USER DETAILS. Place it in the chat-turn flow (input, prompt assembly, generation, render, post-turn, persistence or hub) and name the first stage where actual behavior differs from expected. Read that stage code and its callers, list at most three competing causes and the cheapest observation that separates them, and gather those observations (diagnostics viewer for prompt problems, console and perchanceErrors for runtime problems). Report the confirmed root cause with file, function and evidence, and clearly separate confirmed facts from hypotheses. Do not change code.', fit, src],
    ['dad', 'dad-fix', 'Fix a Dad-Chat bug', 'Make the smallest edit that fixes a confirmed cause.', 'change',
      'Fix the bug in USER DETAILS. First reproduce or confirm the cause by reading the code path in the chat-turn flow. Edit only the function that owns the defect, keep its public window.* names, storage keys and saved-data shapes, and never rewrite or reformat app.js. Follow the HOW TO MAKE ONE SAFE EDIT steps. Re-check the neighboring paths it feeds (render, persistence, export). Report file, function, before and after, and what you actually ran; if you could not run the page, say so.', fit, src],
    // --- Add, improve, build ---
    ['dad', 'dad-add-feature', 'Add a feature to Dad-Chat', 'Place new behavior in the right file, with load order and storage handled.', 'change',
      'Implement the feature in USER DETAILS. Before editing, write a short placement plan: which file (use WHERE NEW CODE BELONGS), which existing function it sits beside, the data it adds (additive fields only), the UI it needs (DOM in index.html or the app, CSS in styling.css), how it persists (existing stores), and what happens to old saved data. Then implement narrowly, feature-detect any new window.* handle where it is called, and escape untrusted text (escHtml, pjsLiteral). Verify the new path and one neighboring existing path. If the request is missing, ask one focused question.', fit, src],
    ['dad', 'dad-improve-feature', 'Improve or enhance an existing feature', 'Observe how it works now, then improve it in small safe steps.', 'change',
      'Improve the existing feature in USER DETAILS. First describe how it works today (file, functions, data, settings, where it appears in the prompt or UI) with evidence from the code. Then make the smallest set of improvements that serve the stated goal, ordered by value and risk, and keep every existing setting, storage key and behavior at its default unless told otherwise. Do not remove old code paths; flag dead-looking code instead. Verify before and after on the same workflow and report what changed.', fit, src],
    ['dad', 'dad-new-module', 'Add a new module or studio file', 'Create a src file, load it in the right order and keep it fail-soft.', 'change',
      'Create the new module described in USER DETAILS as its own src file. Decide whether it needs app.js globals (then load it after app.js like the studios) or must load before app.js. Expose one window.* handle, add the script tag to index.html at that position, add CSS to styling.css, and add a new Perchance import to main.pjs (bridged in pjs-globals.js) only if truly required. Every caller must feature-detect the handle so a missing file cannot break the app. Verify load order, the handle, the feature and a page load with the file removed.', fit, src],
    ['dad', 'dad-prompt-tune', 'Improve prompt assembly or steering text', 'Change what reaches the model without duplicating what is already sent.', 'change',
      'Improve the prompt behavior in USER DETAILS. Locate the block responsible in MemoryEngine.buildHistory (pre-instruction, persona, world, lore, memory, steering) and decide whether it is FIXED (paid every turn) or DYNAMIC. Prefer the cheapest layer that works (reminderMessage, author note, lore entry) over growing the persona. Do not repeat rules the pre-instruction or lorebook already send. Show the exact new text, where it is injected and its character cost per turn, keep the diagnostics preview using the same builder, and verify with the diagnostics viewer.', fit, src],
    ['dad', 'dad-provider-add', 'Add or fix a provider or model', 'Extend the provider catalog without breaking existing routes.', 'change',
      'Add or repair the provider or model in USER DETAILS inside providers.js (window.Dad_PROVIDER_GROUPS). Copy the shape of a neighboring entry in the right group (builtin, cloud, hubs, local runtimes), keep existing ids, route keys through the existing secret handling and never hardcode or log a key. Verify the real API contract (endpoint, auth, streaming, tool support, context limit) from official documentation before writing values and mark unknowns. Check the picker, a successful call, a failure message and that other providers still work.', fit, src],
    ['dad', 'dad-ui-polish', 'Polish Dad-Chat styling and layout', 'Improve CSS and shell markup while keeping first paint intact.', 'change',
      'Improve the interface described in USER DETAILS. Most changes belong in src/styling.css; touch index.html markup only when the DOM must change, and keep the duplicated loading-screen CSS in index.html and styling.css in sync. Use the existing theme variables so theme-customizer still works. Check 360px, 768px and desktop widths, light and dark, long messages, code blocks and loading and error states. Do not rename element ids that app.js or the studios query.', fit, src],
    ['dad', 'dad-import-export', 'Add or repair import and export', 'Keep Dad-native lossless; treat Tavern shapes as share-only.', 'change',
      'Work on the import or export in USER DETAILS. Dad-native is the master: default exports use the dad-char, dad-world and lorebook envelopes from the references, Tavern V2/V3/CCV2/Forge exports are optional and labeled as lossy share copies, and imports may still accept Tavern shapes through the mapping. Always preview before changing anything, never overwrite silently, strip runtime-only fields (lorebookArchive, lastLoreRun, useCount, lastInjectedAt) on export, clamp scanDepth to 20, and keep secrets out of every file. Verify a round trip and a malformed file.', fit, src],
    ['dad', 'dad-hub-work', 'Work on the hub and sharing flow', 'Change client RPC calls and the public server block safely.', 'change',
      'Make the hub change in USER DETAILS. Trace the call from the client hub section in app.js through createServerSocket to the server block in index.html. The server code is public: never put secrets in it, never return owner keys, and keep card bodies in per-user upload files with only metadata and ratings in the index. Keep existing RPC names and shapes working for older clients, validate every argument on the server, and escape displayed text. Verify the happy path and a rejected input.', fit, src],
    // --- Reviews ---
    ['dad', 'dad-prompt-audit', 'Audit prompt assembly and token cost', 'List every block that reaches the model and what it costs per turn.', 'review',
      'Walk the prompt assembly in the order given in the chat-turn flow and list each block: source function, FIXED or DYNAMIC, approximate characters, and whether the diagnostics viewer shows it. Estimate fixed cost per turn for the current character and preset, find duplicated rules between pre-instruction, persona and lorebook, and rank savings by characters per turn. Confirm the preview and the real request use the same builders. Label measured values and estimates separately and do not edit anything.', fit, src],
    ['dad', 'dad-persistence-audit', 'Audit saved data and storage keys', 'Map every store and the risk of changing it.', 'review',
      'Map every place Dad-Chat persists data: localStorage live session, kv.chatApp slots and index, ImageDB, per-thread VFS workspaces, Cloud Backup and settings keys. For each give key or name, shape, writer, reader and how a field rename or addition would affect saved users. Identify corruption, quota and cross-tab risks and what a Cloud Backup restore would lose. Recommend additive, reversible changes only; do not migrate or delete data.', fit, src],
    ['dad', 'dad-safety-review', 'Review rendering, escaping and secrets', 'Trace text and keys from source to sink.', 'review',
      'Trace untrusted text (card fields, lore, chat messages, imported files, hub data) from where it enters to every place it is rendered or sent: markdown through marked and DOMPurify, escHtml for HTML, pjsLiteral for image prompts, toast and modal text, downloads and network calls. Also check for hardcoded or logged keys, tokens and webhook URLs and for secrets in exports or the public server block. Report each source-to-sink path with realistic impact and a narrow fix. Do not execute hostile payloads or change code.', fit, src],
    ['dad', 'dad-perf-size', 'Review size and speed', 'Find what slows load, render or generation.', 'review',
      'Assess startup weight (app.js is about 2.4 MB and loads before first render), lazy-loaded libraries, large threads, lore matching and render cost. Measure what you can (timings, sizes, DOM counts) and label everything else as an estimate. Rank bounded improvements by benefit and risk and say what each would change for saved data. Do not edit code.', fit, src],
    ['dad', 'dad-release-check', 'Check a change before shipping', 'Run a live checklist and list what was not run.', 'review',
      'Run a pre-release check of the touched areas: page load, sending a message, each modal or studio involved, import and export of a dad-char file, theme and narrow-width layout, console errors and perchanceErrors, and storage load of an existing save. Report observed pass or fail with reproduction steps and a separate list of checks you could not run (for example hub upload or a paid provider). Do not publish or change code.', fit, src],
    // --- Content in the Dad-native format ---
    ['dad', 'dad-character-create', 'Write a Dad-native character file', 'Create an importable dad-char JSON from a short brief.', 'review',
      'Create a character from the brief in USER DETAILS and return ONE importable dad-char file (type dad-char, version 2) in a single fenced JSON block; do not edit the generator. Use a new unique id, put a 1-3 sentence bio in description and the persona body in systemPrompt (canon and voice only, never repeating the pre-instruction or lorebook), include 2-3 greetings in firstMessage, 3-5 short example exchanges, a suitable preInstruction, an optional reminderMessage and a few real-named lore entries only if useful. Use only {{char}} and {{user}}, no avatar and no runtime fields. After the JSON list the choices the author should review.', fit, src],
    ['dad', 'dad-character-improve', 'Improve an existing character', 'Fix field placement, duplication and weak voice, with before and after.', 'review',
      'Review the character supplied in USER DETAILS against the Dad-native rules: bio versus persona placement, one fact once, no repetition of the pre-instruction or lorebook, greetings as hooks, short in-voice example dialogue and sensible reminder text. Return a table of changes (field, before, after, reason, characters saved) and then the complete improved dad-char JSON in one fenced block. Keep greetings and example exchanges verbatim unless the user asks, do not invent canon and flag guesses. Do not edit the generator.', fit, src],
    ['dad', 'dad-lore-build', 'Build Dad-native lore entries', 'Turn source text into well-keyed, small lore entries.', 'review',
      'Turn the source material in USER DETAILS into lore entries and return a standalone lorebook (version 2.0 envelope) or entries for the named character in one fenced JSON block. Each entry has a real name, 3-6 lowercase keys that do not appear in any other entry, content of 45 words or fewer in the pattern Name - role. Fact. Fact. Voice cue. Constraint., an explicit priority, constant false (at most 2 true per book), scanDepth null and enabled true. Tag facts taken from the source as established and anything you add as proposed. Do not edit the generator.', fit, src],
    ['dad', 'dad-lore-audit', 'Audit a lorebook', 'Find key overlap, oversized entries and budget waste.', 'review',
      'Audit the lorebook or character lore supplied in USER DETAILS: keys shared between entries, entries named Entry N, content over 45 words, scanDepth other than null (especially 50), more than 2 constant entries, repeated facts, vectorized entries without embeddings and disabled entries. Estimate the characters each entry spends against the 6,656-character lore budget and which entries would be budget_cut together. Report findings by severity with the entry name and a concrete fix; do not rewrite entries unless asked and do not edit the generator.', fit, src],
    ['dad', 'dad-world-build', 'Build a Dad-native world', 'Write the world bible and linked entries as a dad-world file.', 'review',
      'Create the world described in USER DETAILS and return ONE dad-world file (type dad-world, version 1) in a single fenced JSON block. The description states what every character in the world knows (always injected, keep it focused) and entries carry places, factions, rules and rumors, each following the lore entry rules (real name, 3-6 unique keys, about 45 words, scanDepth null, at most 2 constant). Avoid telling the same fact in several entries. Do not edit the generator.', fit, src],
    ['dad', 'dad-token-diet', 'Cut fixed prompt cost without losing canon', 'Apply the Henry Tucker cut order to a persona and lore.', 'review',
      'Reduce the fixed per-turn cost of the character in USER DETAILS using the cost-control cut order: remove duplicates of the pre-instruction first, then merge overlapping lore entries, then tighten long descriptive blocks, then scenario. Keep greetings and example exchanges verbatim, keep every distinct fact and the speech patterns, and mark any uncertain cut as author to confirm. Report characters before and after for each field and the total fixed chars per turn, then give the revised JSON. Do not invent canon or edit the generator.', fit, src],
    ['dad', 'dad-convert-tavern', 'Convert a Tavern V2/V3 card to Dad-native', 'Map a card and its lorebook into dad-char and say what is lost.', 'review',
      'Convert the Tavern card or lorebook in USER DETAILS to Dad-native using the mapping reference: description to systemPrompt (plus scenario and examples if they have no slot), personality to the bio, first_mes and alternate_greetings to firstMessage, system_prompt to a custom pre-instruction, post_history_instructions to reminderMessage and character_book to lorebook with real entry names, 3-6 keys, priority and scanDepth clamped to null or 20. Return the dad-char JSON in one fenced block followed by a list of dropped or lossy fields (selective, probability, sticky, cooldown, delay, group and non-forge extensions) with the affected entries. Do not edit the generator.', fit, src],
    ['dad', 'dad-greetings-examples', 'Write greetings and example dialogue', 'Hooks and voice samples for a character.', 'review',
      'Write opening messages and example dialogue for the character in USER DETAILS. Greetings are hooks: each a different situation of 2-4 sentences that ends with something {{user}} can answer, with greeting one as the default opening and the rest as alternates. Example dialogue is 3-6 exchanges, each side under 40 words, entirely in voice, never narrating {{user}} actions. Return them in the firstMessage and exampleDialogue shapes of the dad-char format in one fenced JSON block. Do not edit the generator.', fit, src]
  ];
  return Object.freeze({ rows });
});
