/* AI image prompt skills (section "imagegen"), adapted from ideas in two public Nano Banana Pro prompt collections.
   Original task wording; no prompts or images from those collections are bundled. Plain data, no network or editor access. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.WeldSkillsImage = factory();
})(typeof window === 'object' ? window : globalThis, function () {
  'use strict';
  // [category, id, title, description, mode, task, fit, sources]
  const img = ['image'], src = ['nano', 'nanoym'];
  const rows = [
    // --- Prompt libraries, templates and builders ---
    ['imagegen', 'img-prompt-library', 'Build an image prompt library & gallery', 'Browse, search, tag and reuse ready-made prompts with example slots.', 'change',
      'Add a prompt library to this generator: a searchable grid of prompt cards grouped by the PROMPT LIBRARY CATEGORIES in the reference (portraits, creative experiments, education, e-commerce, workplace, photo editing, interior design, social media, daily life, avatars). Each card shows title, one-line description, tags, a short preview of the prompt, and buttons Use (fill the generator prompt box, never auto-generate), Copy, Favorite and Details. Store the library as data in the template model from the reference, keep user-added prompts separate from built-ins, and cap the visible count with Show more. Seed it with a small set of original prompts written for this generator, not copied from other collections. Render all prompt text as text. Verify search, tag filters, an empty result, favorites after reload and a very long prompt.', img, src],
    ['imagegen', 'img-prompt-slots', 'Add fill-in-the-blank prompt templates', 'Turn a prompt into labeled fields with defaults and a live preview.', 'change',
      'Add templates whose changeable parts are named slots (see SLOT SYNTAX in the reference). Parse slots from the template, build one labeled input per unique slot with its default as placeholder, show the filled prompt live, and mark unfilled slots clearly. Defaults must produce a good image on their own, so Generate works with zero edits. Support the same slot used twice, slots inside quoted text, a literal brace via escaping and unknown slot names without breaking. Never evaluate slot values as code or HTML, cap value length, keep the template text unchanged when saving values, and let the user save, rename and delete filled presets. Verify empty values, repeated slots, special characters and a template with no slots.', img, src],
    ['imagegen', 'img-json-prompt-builder', 'Add a structured (JSON) prompt builder', 'Edit subject, photography, background and avoid-list as fields, send as JSON or plain text.', 'change',
      'Add a builder that edits the prompt as structured fields (subject, clothing or details, accessories, photography with camera style, lighting, angle and texture, background, and an avoid list) following the STRUCTURED PROMPT shape in the reference. Keep the object in one state value, show a live JSON view, and offer a switch to flatten it into a readable paragraph for models that handle prose better. Validate types, drop empty keys, cap sizes, and let the user import and export the JSON. Check the real image plugin or model call to see whether it accepts a long structured prompt before sending JSON, and fall back to the flattened text. Keep any instruction like preserve the original face as its own field. Verify empty fields, nested arrays, invalid imported JSON and very long values.', img, src],
    ['imagegen', 'img-photo-composer', 'Add a photo style composer with chips', 'Pick lens, lighting, era, mood and finish from labeled options.', 'change',
      'Add a composer of option groups that assemble prompt clauses: camera and lens (for example 35mm wide, 85mm portrait, fisheye, compact digital), lighting (flash, golden hour, soft window, rim light), era or film look, color grade, depth of field, composition and finish. Use the PROMPT ANATOMY order from the reference, show the clause each chip adds on hover, allow at most one chip per exclusive group, and show the combined prompt before generating. Include a Reset and a Random combination button that respects the exclusive groups. Do not add claims such as 8K or award-winning unless the user picks them. Keep the user own prompt text in its own field and append clauses after it. Verify conflicting chips, no chips and rapid toggling.', img, src],
    // --- Editing with reference images ---
    ['imagegen', 'img-reference-edit', 'Add reference-image editing with identity lock', 'Upload one or more images and edit them while keeping faces and details.', 'change',
      'Add an edit mode where the user supplies one to three reference images and a short instruction. Label images Image 1, Image 2 and Image 3 in the UI and in the prompt so instructions can refer to them. Add an Identity lock switch that appends a clear preserve-the-face-and-features clause, and a Preserve list (logos, texture, colors, pose, background). Before using any photo of a real person show a one-time consent line that the user has the right to use it, and apply the LIKENESS AND CONSENT rules in the reference. Verify the real plugin accepts image input and in what form (url, data URL or blob) from its source before wiring it, and say plainly when it does not. Check file type and size, show thumbnails with Remove, never upload anything automatically, and release object URLs. Verify no image, a wrong file type, an oversized file and three images.', img, src],
    ['imagegen', 'img-edit-recipes', 'Add one-click photo fix & edit recipes', 'Outpaint, remove crowds, restore, colorize, translate text and more.', 'change',
      'Add a recipe picker for common edits using the EDIT RECIPES in the reference: outpaint to a new aspect ratio, remove people or objects, restore and colorize old photos, replace the background, relight, fix a tilted or cropped composition, and translate visible text in an image. Each recipe shows what it needs (one image, a target ratio, a language), builds its prompt with a built-in Preserve clause, and lets the user edit the prompt before sending. Offer a Compare view (original and result) and keep the original untouched. Do not promise exact results, and tell the user when the plugin cannot accept an input image. Verify each recipe with missing input, a changed ratio and Cancel.', img, src],
    // --- Purpose-built studios ---
    ['imagegen', 'img-infographic-studio', 'Add a concept-to-infographic studio', 'Describe a topic, pick style and language, get a labeled educational image.', 'change',
      'Add a studio that turns a topic into an educational infographic prompt: topic, audience level, visual style (flat vector, textbook, sketch, bento grid, flow chart, Sankey), language for labels, and a list of the elements and arrows the user wants. Optionally ask the text model to list the key components first (return a short validated list) and let the user edit it before the image is requested. State that label spelling and numbers in generated images must be checked by a person, add a Regenerate with corrections field, and offer a plain text version of the content as a fallback. Do not invent facts or statistics; ask the user to supply data for charts. Verify a two-word topic, a long topic, a non-English label language and an empty element list.', img, src],
    ['imagegen', 'img-cover-poster-studio', 'Add a cover, thumbnail & poster studio', 'Compose text-on-image designs with exact wording and safe layout.', 'change',
      'Add a studio for covers, video thumbnails, quote cards, posters and magazine covers. Fields: headline text (exact wording in quotes), optional subtitle, subject or reference image, layout (subject left and text right, centered, full bleed), mood, colors, and format presets with their aspect ratios (16:9, 9:16, 1:1, 4:5, A-series paper). Put every text string in quotes in the prompt, state font feel, outline or shadow for contrast and position, and add a legible-text check reminder. Keep headlines short (warn above about eight words), keep important text inside a safe margin, and keep a text-free version option so the user can add real type later. Verify long text, quotes and apostrophes inside text, non-Latin scripts and each format.', img, src],
    ['imagegen', 'img-product-studio', 'Add a product, try-on & virtual studio', 'Place products and garments in clean studio, lifestyle or model shots.', 'change',
      'Add a product studio: product image or description, scene presets (white seamless, marble, lifestyle room, outdoor, floating with shadow), lighting and camera options, a brand color, and optional model try-on where a garment image and a model image are labeled Image 1 and Image 2. Add Preserve controls for fabric texture, color and logos, and a natural-fit clause for drape, folds and shadows that match the scene lighting. Add a batch for angles and backgrounds with a bounded count and a visible cost estimate when the plugin has one. Do not invent logos, certifications or claims, and mark outputs as AI illustrations for listing use. Verify missing product image, mismatched sizes, transparent PNG and a batch cancel.', img, src],
    ['imagegen', 'img-avatar-pack', 'Add avatar, sticker & multi-pose sets', 'Generate a matching set from one description or reference.', 'change',
      'Add a set generator: choose a style (blind-box figure, chibi, pet meme, sticker, Y2K scrapbook, game portrait, profile avatar), one subject description or a labeled reference image, and a number of poses or expressions from an editable list. Build one shared style block plus a short per-item line so the set stays consistent, generate with bounded concurrency and show a contact sheet with Retry per item. Offer a transparent-or-plain background option and a text-free option for sticker use. Apply the LIKENESS AND CONSENT rules for real people, never auto-start a large batch and show the count before running. Verify one item failing, Stop mid-batch and re-running only the failed items.', img, src],
    ['imagegen', 'img-storyboard-keyframes', 'Add a storyboard & keyframe planner', 'Turn one image or idea into a continuous set of cinematic shots.', 'change',
      'Add a planner that takes one reference image or a short description and produces 3 to 8 shots. Step 1 asks the text model to describe only what is visible (subjects, layout, light, time of day) and list 3 to 6 visual anchors that must stay constant. Step 2 proposes a theme and a short setup, build, turn, payoff arc. Step 3 writes a prompt per shot with shot size, angle, camera move and action, repeating the anchors so subjects, wardrobe, setting and color grade stay continuous, and never adding new characters. Show shots as editable cards with reorder, regenerate and copy. Validate all model replies as JSON, never guess real identities, places or brands, and keep it a planning aid, not an automatic video render. Verify one-shot, eight-shot and a malformed model reply.', img, src],
    ['imagegen', 'img-diorama-presets', 'Add isometric, miniature & 3D scene presets', 'Place a city, room, object or story into a collectible miniature look.', 'change',
      'Add a preset set for miniature and 3D looks: isometric room or office, city or country diorama with landmarks, floating island, tiny pool or street scene, ornament or figure, 3D map, and storefront in a chibi or toy style. Each preset has a slot for the place or subject (for example a city name) and fixed clauses for viewing angle, scale, material (clay, plastic, glass, paper), soft studio lighting, tilt-shift depth and a clean background. Add a landmark list the user can edit, an aspect ratio and an optional caption text slot. Do not assert that landmarks are accurate; ask the user to check. Verify an unknown place, a long list of landmarks and each preset with default slots.', img, src],
    // --- Prompt quality, variation and safety ---
    ['imagegen', 'img-prompt-lint', 'Review image prompts for common problems', 'Find vague, conflicting or unsafe wording before it is sent.', 'review',
      'Inspect how this generator builds image prompts and review sample prompts it produces. Check against the PROMPT ANATOMY in the reference: missing subject, vague words with no visual meaning, contradictory lighting or style, too many ideas in one sentence, text that is not in quotes, missing aspect ratio, identity instructions stated once or not at all in edit prompts, negative lists that mention the unwanted thing without need, and boilerplate such as repeated 8K or award-winning claims. Report each finding with the sample, why it hurts the result, and a minimal rewrite. List what could not be checked without generating images. Do not change code.', img, src],
    ['imagegen', 'img-ab-variations', 'Add A/B prompt variations and side-by-side compare', 'Try two or more wordings or settings and keep the winner.', 'change',
      'Add a compare mode that runs the same idea with up to four variants (different wording, style chip or one setting) and shows results side by side with their prompts. Cap the count, show the total number of requests before running, run with bounded concurrency, allow Stop, keep partial results and mark which prompt made which image. Add Keep this one, which saves the winning prompt as a preset, and a note field per variant. Never run automatically and never retry failures silently. Verify one failed variant, Stop, and a repeated run that must not mix old images into new slots.', img, src],
    ['imagegen', 'img-aspect-presets', 'Add aspect ratio & size presets', 'One picker that fits wallpapers, covers, avatars and print.', 'change',
      'Add an aspect ratio and size picker with presets: square 1:1, portrait 3:4 and 4:5, story 9:16, wide 16:9 and 21:9, plus a custom ratio. Read what the actual image plugin supports (named ratios, width and height, or none) from its source and map the choice to it; when it supports only the prompt text, add the ratio to the prompt and say so. Show a framing preview box, remember the last choice, and warn when the choice may crop text or faces. Never invent plugin options. Verify each preset, a custom value out of range and an unsupported plugin.', img, src],
    ['imagegen', 'img-import-credit', 'Import prompt collections with source credit', 'Bring in markdown or JSON prompts and keep author, link and license.', 'change',
      'Add an importer for prompt collections in markdown (headings with a fenced prompt and a source line) and in JSON. Parse into the template model from the reference: title, prompt, tags, language, author, source link and license. Preview the parsed items with duplicates and rejects marked, let the user select which to add, and never import automatically. Keep credit visible on every imported card with a link, store the license note, and block items with no prompt text. Treat all imported text and links as untrusted: render as text, allow only http and https links and cap size and count. Do not bundle third-party prompts into the generator itself. Verify a malformed file, 500 items, a duplicate and a missing source.', img, src],
    ['imagegen', 'img-likeness-guard', 'Add consent, likeness & labeling safeguards', 'Handle real people, public figures and AI disclosure responsibly.', 'change',
      'Apply the LIKENESS AND CONSENT rules from the reference to this generator. Add a visible consent checkbox before any photo of a real person is used, block or warn on prompts that ask for a named real person in a misleading, intimate, political or deceptive scene, and never use the output to imply endorsement. Add an optional AI-generated label or caption to saved and downloaded images and keep it editable. Keep uploaded reference images local, do not log them, and give a Clear button. Do not claim the filter is complete. Verify a named public figure, a minor-looking subject in an edit request, an empty consent state and a download with the label on and off.', img, src]
  ];
  return Object.freeze({ rows });
});
